[platformio]
default_envs = STM32F103CB

[env]
platform = ststm32

framework = arduino
upload_protocol = stlink
debug_tool = stlink
build_type = debug

lib_deps =
    Wire
    SPI
    olikraus/U8g2
    mathertel/OneButton
    snakeye/RecurringTask

[env:bluepill]
board = bluepill_f103c8

[env:STM32F103CB]
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6