[platformio]
default_envs = STM32G431C8T6

[env]
platform = ststm32

framework = arduino
upload_protocol = stlink
debug_tool = stlink

build_type = debug
; build_flags = -O2
; build_unflags = -Os

lib_deps =
    Wire
    SPI
    wollewald/ADS1220_WE
    olikraus/U8g2
    mathertel/OneButton
    snakeye/RecurringTask

[env:bluepill]
board = bluepill_f103c8

[env:STM32G431C8T6]
board = genericSTM32G431C8
board_build.mcu = stm32g431c8t6