[platformio]
default_envs = STM32G431C8T6_release

[env]
platform = ststm32

framework = arduino
upload_protocol = stlink
debug_tool = stlink

lib_deps =
    Wire
    SPI
    wollewald/ADS1220_WE
    olikraus/U8g2
    mathertel/OneButton
    snakeye/RecurringTask

[env:STM32G431C8T6_release]
board = genericSTM32G431C8
board_build.mcu = stm32g431c8t6
build_type = release
build_flags = -O2
build_unflags = -Os

[env:STM32G431C8T6_debug]
board = genericSTM32G431C8
board_build.mcu = stm32g431c8t6
build_type = debug
